### PR TITLE
Add html tags and their explanation.

### PR DESCRIPTION
**Pull request by SajidAnTechie**

### CODE REVIEW

**Comment by SajidAnTechie** [comment]
Consider for hacktoberfest 2021 @AnuragAnalog

**Review by AnuragAnalog — APPROVED** [review]
These are looking good

**Comment by AnuragAnalog** [comment]
@SajidAnTechie, your pull request has been accepted.

**Comment by SajidAnTechie** [comment]
@AnuragAnalog you should label 'hacktoberfest-accepted'

**Comment by SajidAnTechie** [comment]
@AnuragAnalog could you just add 'hacktoberfest-accepted' label in this PR. Thank you !!

**Pull request merged**
